services:
  - type: web
    name: bazfez-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: bazfez-bot
          property: host